from_latest_tag = false
ignore_merge_commits = false
generate_mono_repository_global_tag = true
branch_whitelist = []
skip_untracked = false
pre_bump_hooks = [
    "sed -i -E 's/^version.*$/version = \"{{version}}\"/' Cargo.toml",
    "sed -i -E 's/v[0-9].[0-9].[0-9]/v{{version}}/' man/envelope.1.md",
    "cargo check",
]
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]

[packages]
