name: Build Binary for Multiple Platforms

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  build:
    name: Build for Multiple Platforms
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - build: x86_64
            os: ubuntu-latest
            architecture: x86_64
            target: x86_64-unknown-linux-gnu

          - build: arm
            os: ubuntu-latest
            architecture: arm
            target: arm-unknown-linux-gnueabihf

          - build: arm64
            os: ubuntu-latest
            architecture: aarch64
            target: aarch64-unknown-linux-gnu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Rust for the build
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/master' }}

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}

      - name: File
        run: file target/${{ matrix.target }}/release/envelope

      - name: Rename
        run: mv target/${{ matrix.target }}/release/envelope target/${{ matrix.target }}/release/envelope-${{ matrix.architecture }}

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/${{ matrix.target }}/release/envelope-${{ matrix.architecture }}
